version: '3.8'

services:

  avaliacao:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: avtecnica

    environment:
      - SPRING_PROFILES_ACTIVE=test,docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pauta
      - DB_HOSTNAME=postgres
      - POSTGRES_PASSWORD=colognow
      - POSTGRES_USER=admin
    ports:
      - "8080:8080"
      - "8083:8083"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pauta
      - POSTGRES_PASSWORD=colognow
      - POSTGRES_USER=admin
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
   pgdata:
